language: go

arch:
  - AMD64
  - ppc64le

notificaitons:
  email:
    recipients: bluesuncorp01@gmail.com
    on_success: change
    on_failure: always

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip
